"""empty message

Revision ID: 3b22455cc8dd
Revises: None
Create Date: 2016-03-09 22:59:30.972509

"""

# revision identifiers, used by Alembic.
revision = '3b22455cc8dd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cards', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck')
    ### end Alembic commands ###
