"""empty message

Revision ID: 9dc9fb4f977b
Revises: 3b22455cc8dd
Create Date: 2016-03-10 14:11:58.749503

"""

# revision identifiers, used by Alembic.
revision = '9dc9fb4f977b'
down_revision = '3b22455cc8dd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('data', postgresql.JSON(), nullable=True))
    op.drop_column('deck', 'cards')
    op.drop_column('deck', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deck', sa.Column('cards', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('deck', 'data')
    ### end Alembic commands ###
